// Run with inputs exported by tools/export-fh1-layered-geometry.py.
// This validates captured geometry import, not live resource lifetime
// ownership.
#define WIN32_LEAN_AND_MEAN
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <optional>
#include <span>
#include <stdexcept>
#include <vector>
#include <windows.h>
#include <wrl/client.h>
using Microsoft::WRL::ComPtr;
// Generated bytecode headers require the Windows BYTE definition above.
#include "../../thirdparty/shiftglue-sdk/src/graphics/shaders/bytecode/d3d12_5_1/fh1_layered_scene_vs.h"
static void check(HRESULT hr) {
  if (FAILED(hr))
    throw std::runtime_error("D3D12 failure " + std::to_string(unsigned(hr)));
}
static std::vector<char> read(const std::filesystem::path &path) {
  std::ifstream file(path, std::ios::binary);
  if (!file)
    throw std::runtime_error("Missing input " + path.string());
  return {std::istreambuf_iterator<char>(file), {}};
}
#include "../../thirdparty/shiftglue-sdk/include/rex/graphics/d3d12/fh1_geometry.h"
using rex::graphics::d3d12::geometry_range;

static void check_geometry_bounds() {
  auto require = [](bool value) {
    if (!value)
      throw std::runtime_error("Geometry bounds regression");
  };
  std::array<uint32_t, 8> system{0, 0, 0, UINT32_MAX, 0, 0, 0, 0xFFFFFF};
  require(geometry_range(system, .25f, 120, 0x1003, 1200).has_value());
  require(!geometry_range(system, .25f, 125, 0x1003, 1200));
  require(!geometry_range(system, 1.f, 120, 0x1003, 1200));
  require(!geometry_range(system, .25f, 0, 0x1003, 1200));
  require(!geometry_range(system, .25f, 120, 0x1FFFFF03, 1200));
  require(!geometry_range(system, -1.f, 120, 0x1003, 1200));
  require(!geometry_range(system, std::numeric_limits<float>::infinity(), 120,
                          0x1003, 1200));
  require(!geometry_range(system, std::numeric_limits<float>::quiet_NaN(), 120,
                          0x1003, 1200));
  for (auto [slot, value] :
       {std::pair{0u, 1u}, {4u, 2u}, {5u, 0xFFFFFFu}, {6u, 0x1000000u}}) {
    auto invalid = system;
    invalid[slot] = value;
    require(!geometry_range(invalid, .25f, 120, 0x1003, 1200));
  }
  system[3] = 0;
  require(geometry_range(system, .25f, 120, 0x1003, 1200).has_value());
  // Exhaustively check accepted small ranges against individual vertex loads.
  for (uint32_t offset = 0; offset < 16; ++offset)
    for (uint32_t count = 1; count < 41; ++count)
      for (float scale : {0.f, .25f, .5f, 1.f, 1.5f})
        for (uint32_t size : {40u, 80u, 120u, 400u, 1200u}) {
          system[5] = offset;
          if (!geometry_range(system, scale, count, 0x1003, size))
            continue;
          for (uint32_t id = 0; id < count; ++id)
            require((uint64_t(std::floor(float(id + offset) * scale)) + 1) *
                        40 <=
                    size);
        }
}
int main(int argc, char **argv) try {
  check_geometry_bounds();
  if (argc == 2 && !std::strcmp(argv[1], "--self-test")) {
    std::cout << "Geometry bounds checks passed\n";
    return 0;
  }
  if (argc < 2 || argc > 3)
    throw std::runtime_error(
        "Usage: check-owned-layered-geometry INPUT_DIR [--poison]");
  const bool poison = argc == 3;
  if (poison && std::strcmp(argv[2], "--poison"))
    throw std::runtime_error("Unknown option");
  const std::filesystem::path dir = argv[1];
  auto vertices = read(dir / "vertices.bin"), system = read(dir / "b0.bin"),
       constants = read(dir / "b1.bin"), fetch = read(dir / "b3.bin"),
       expected = read(dir / "postvs.bin");
  if (vertices.size() != 1200 || system.size() < 480 ||
      constants.size() < 400 || fetch.size() < 768 || expected.size() != 9600)
    throw std::runtime_error("Fixture size mismatch");
  system.resize(480);
  constants.resize(400);
  fetch.resize(768);
  uint32_t flags;
  std::memcpy(&flags, system.data(), 4);
  if (flags & 1)
    throw std::runtime_error("Fixture requires UAV geometry");
  std::array<uint32_t, 8> system_words;
  std::memcpy(system_words.data(), system.data(), sizeof(system_words));
  uint32_t fetch_address, fetch_size;
  float index_scale;
  std::memcpy(&fetch_address, fetch.data() + 190 * 4, 4);
  std::memcpy(&fetch_size, fetch.data() + 191 * 4, 4);
  std::memcpy(&index_scale, constants.data() + 23 * 16, 4);
  const auto qualified_geometry_range =
      geometry_range(system_words, index_scale, 120, fetch_address, fetch_size);
  if (!qualified_geometry_range ||
      qualified_geometry_range->second != vertices.size())
    throw std::runtime_error(
        "Geometry fetch exceeds the owned buffer contract");
  // Import the captured geometry into its own buffer. The shader fetch base
  // uses a nonzero offset within an aligned view; packed bytes and live constants stay
  // intact.
  uint32_t fetch_base = 7;  // Four-byte fetch offset within the aligned SRV.
  std::memcpy(fetch.data() + 190 * 4, &fetch_base, 4);
  if (poison)
    vertices[0] ^= char(0x80);
  ComPtr<ID3D12Debug> debug;
  if (SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))
    debug->EnableDebugLayer();
  ComPtr<IDXGIFactory6> factory;
  check(CreateDXGIFactory2(0, IID_PPV_ARGS(&factory)));
  ComPtr<IDXGIAdapter1> adapter;
  check(factory->EnumAdapterByGpuPreference(
      0, DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE, IID_PPV_ARGS(&adapter)));
  DXGI_ADAPTER_DESC1 adapter_desc;
  check(adapter->GetDesc1(&adapter_desc));
  ComPtr<ID3D12Device> device;
  check(D3D12CreateDevice(adapter.Get(), D3D_FEATURE_LEVEL_11_0,
                          IID_PPV_ARGS(&device)));
  auto buffer =
      [&](uint64_t size, D3D12_HEAP_TYPE heap, D3D12_RESOURCE_STATES state,
          D3D12_RESOURCE_FLAGS resource_flags = D3D12_RESOURCE_FLAG_NONE) {
        D3D12_HEAP_PROPERTIES properties = {};
        properties.Type = heap;
        D3D12_RESOURCE_DESC desc = {};
        desc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
        desc.Width = size;
        desc.Height = 1;
        desc.DepthOrArraySize = 1;
        desc.MipLevels = 1;
        desc.SampleDesc.Count = 1;
        desc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
        desc.Flags = resource_flags;
        ComPtr<ID3D12Resource> resource;
        check(device->CreateCommittedResource(&properties, D3D12_HEAP_FLAG_NONE,
                                              &desc, state, nullptr,
                                              IID_PPV_ARGS(&resource)));
        return resource;
      };
  auto upload = [&](const std::vector<char> &data) {
    auto resource =
        buffer((data.size() + 255) & ~uint64_t(255), D3D12_HEAP_TYPE_UPLOAD,
               D3D12_RESOURCE_STATE_GENERIC_READ);
    void *mapped;
    D3D12_RANGE empty = {};
    check(resource->Map(0, &empty, &mapped));
    std::memcpy(mapped, data.data(), data.size());
    resource->Unmap(0, nullptr);
    return resource;
  };
  auto geometry_upload = upload(vertices);
  auto geometry_source = buffer(vertices.size(), D3D12_HEAP_TYPE_DEFAULT,
                                D3D12_RESOURCE_STATE_COPY_DEST);
  auto geometry = buffer(vertices.size() + 32, D3D12_HEAP_TYPE_DEFAULT,
                         D3D12_RESOURCE_STATE_COPY_DEST);
  auto cb0 = upload(system), cb1 = upload(constants), cb3 = upload(fetch);
  constexpr uint64_t output_bytes = 9600;
  auto output = buffer(output_bytes + 8, D3D12_HEAP_TYPE_DEFAULT,
                       D3D12_RESOURCE_STATE_COPY_DEST);
  auto readback = buffer(output_bytes + 8, D3D12_HEAP_TYPE_READBACK,
                         D3D12_RESOURCE_STATE_COPY_DEST);
  auto initial = upload(std::vector<char>(output_bytes + 8));
  D3D12_ROOT_PARAMETER parameters[4] = {};
  for (UINT i = 0; i < 4; ++i) {
    parameters[i].ParameterType =
        i < 3 ? D3D12_ROOT_PARAMETER_TYPE_CBV : D3D12_ROOT_PARAMETER_TYPE_SRV;
    parameters[i].Descriptor.ShaderRegister = i < 2 ? i : i == 2 ? 3 : 0;
    parameters[i].ShaderVisibility = D3D12_SHADER_VISIBILITY_VERTEX;
  }
  D3D12_ROOT_SIGNATURE_DESC root_desc = {
      4, parameters, 0, nullptr, D3D12_ROOT_SIGNATURE_FLAG_ALLOW_STREAM_OUTPUT};
  ComPtr<ID3DBlob> serialized, errors;
  check(D3D12SerializeRootSignature(&root_desc, D3D_ROOT_SIGNATURE_VERSION_1,
                                    &serialized, &errors));
  ComPtr<ID3D12RootSignature> root;
  check(device->CreateRootSignature(0, serialized->GetBufferPointer(),
                                    serialized->GetBufferSize(),
                                    IID_PPV_ARGS(&root)));
  D3D12_SO_DECLARATION_ENTRY declarations[] = {{0, "SV_Position", 0, 0, 4, 0},
                                               {0, "TEXCOORD", 0, 0, 4, 0},
                                               {0, "TEXCOORD", 1, 0, 4, 0},
                                               {0, "TEXCOORD", 2, 0, 4, 0},
                                               {0, "TEXCOORD", 3, 0, 4, 0}};
  UINT stride = 80;
  D3D12_GRAPHICS_PIPELINE_STATE_DESC desc = {};
  desc.pRootSignature = root.Get();
  desc.VS = {fh1_layered_scene_vs, sizeof(fh1_layered_scene_vs)};
  desc.StreamOutput = {declarations, 5, &stride, 1,
                       D3D12_SO_NO_RASTERIZED_STREAM};
  desc.SampleMask = UINT_MAX;
  desc.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
  desc.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
  desc.DepthStencilState.DepthFunc = D3D12_COMPARISON_FUNC_ALWAYS;
  desc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT;
  desc.SampleDesc.Count = 1;
  ComPtr<ID3D12PipelineState> pipeline;
  check(device->CreateGraphicsPipelineState(&desc, IID_PPV_ARGS(&pipeline)));
  ComPtr<ID3D12CommandQueue> queue;
  D3D12_COMMAND_QUEUE_DESC queue_desc = {};
  check(device->CreateCommandQueue(&queue_desc, IID_PPV_ARGS(&queue)));
  ComPtr<ID3D12CommandAllocator> allocator;
  check(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,
                                       IID_PPV_ARGS(&allocator)));
  ComPtr<ID3D12GraphicsCommandList> commands;
  check(device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT,
                                  allocator.Get(), pipeline.Get(),
                                  IID_PPV_ARGS(&commands)));
  auto barrier = [&](ID3D12Resource *resource, D3D12_RESOURCE_STATES before,
                     D3D12_RESOURCE_STATES after) {
    D3D12_RESOURCE_BARRIER b = {};
    b.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    b.Transition = {resource, D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES, before,
                    after};
    commands->ResourceBarrier(1, &b);
  };
  commands->CopyBufferRegion(geometry_source.Get(), 0, geometry_upload.Get(), 0,
                             vertices.size());
  barrier(geometry_source.Get(), D3D12_RESOURCE_STATE_COPY_DEST,
          D3D12_RESOURCE_STATE_INDEX_BUFFER |
              D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE |
              D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE |
              D3D12_RESOURCE_STATE_COPY_SOURCE);
  commands->CopyBufferRegion(geometry.Get(), 20, geometry_source.Get(), 0,
                             vertices.size());
  barrier(geometry.Get(), D3D12_RESOURCE_STATE_COPY_DEST,
          D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
  commands->CopyBufferRegion(output.Get(), 0, initial.Get(), 0,
                             output_bytes + 8);
  barrier(output.Get(), D3D12_RESOURCE_STATE_COPY_DEST,
          D3D12_RESOURCE_STATE_STREAM_OUT);
  commands->SetGraphicsRootSignature(root.Get());
  commands->SetGraphicsRootConstantBufferView(0, cb0->GetGPUVirtualAddress());
  commands->SetGraphicsRootConstantBufferView(1, cb1->GetGPUVirtualAddress());
  commands->SetGraphicsRootConstantBufferView(2, cb3->GetGPUVirtualAddress());
  commands->SetGraphicsRootShaderResourceView(3,
                                              geometry->GetGPUVirtualAddress() + 16);
  commands->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_POINTLIST);
  D3D12_STREAM_OUTPUT_BUFFER_VIEW view = {
      output->GetGPUVirtualAddress(), output_bytes,
      output->GetGPUVirtualAddress() + output_bytes};
  commands->SOSetTargets(0, 1, &view);
  commands->DrawInstanced(120, 1, 0, 0);
  barrier(output.Get(), D3D12_RESOURCE_STATE_STREAM_OUT,
          D3D12_RESOURCE_STATE_COPY_SOURCE);
  commands->CopyResource(readback.Get(), output.Get());
  check(commands->Close());
  ID3D12CommandList *lists[] = {commands.Get()};
  queue->ExecuteCommandLists(1, lists);
  ComPtr<ID3D12Fence> fence;
  check(device->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(&fence)));
  check(queue->Signal(fence.Get(), 1));
  HANDLE event = CreateEvent(nullptr, FALSE, FALSE, nullptr);
  if (!event)
    throw std::runtime_error("CreateEvent failed");
  HRESULT wait_hr = fence->SetEventOnCompletion(1, event);
  if (FAILED(wait_hr)) {
    CloseHandle(event);
    check(wait_hr);
  }
  DWORD waited = WaitForSingleObject(event, 30000);
  CloseHandle(event);
  if (waited != WAIT_OBJECT_0)
    throw std::runtime_error("GPU wait failed");
  check(device->GetDeviceRemovedReason());
  ComPtr<ID3D12InfoQueue> messages;
  if (SUCCEEDED(device.As(&messages))) {
    for (UINT64 i = 0; i < messages->GetNumStoredMessages(); ++i) {
      SIZE_T size = 0;
      check(messages->GetMessage(i, nullptr, &size));
      std::vector<char> storage(size);
      auto *message = reinterpret_cast<D3D12_MESSAGE *>(storage.data());
      check(messages->GetMessage(i, message, &size));
      if (message->Severity <= D3D12_MESSAGE_SEVERITY_ERROR)
        throw std::runtime_error(message->pDescription);
    }
  }
  void *mapped;
  D3D12_RANGE range = {0, output_bytes + 8};
  check(readback->Map(0, &range, &mapped));
  uint64_t written;
  std::memcpy(&written, static_cast<char *>(mapped) + output_bytes, 8);
  size_t differences = 0;
  for (size_t i = 0; i < expected.size(); ++i)
    differences += expected[i] != static_cast<char *>(mapped)[i];
  std::ofstream result(dir / (poison ? "owned-poison.bin" : "owned-postvs.bin"),
                       std::ios::binary);
  result.write(static_cast<char *>(mapped), output_bytes);
  result.close();
  if (!result)
    throw std::runtime_error("Unable to write geometry output");
  D3D12_RANGE empty = {};
  readback->Unmap(0, &empty);
  std::wcout << adapter_desc.Description << L"\n";
  std::cout << "owned geometry bytes=" << vertices.size()
            << " output bytes=" << written
            << " mismatched bytes=" << differences << " poison=" << poison
            << "\n";
  if (written != output_bytes || (poison ? differences == 0 : differences != 0))
    throw std::runtime_error("Native geometry comparison failed");
  return 0;
} catch (const std::exception &e) {
  std::cerr << e.what() << "\n";
  return 1;
}
